### ISSUE TITLE
Add a way to customize the default theme

### ISSUE THREAD

**Issue by acoul** [netjson/django-netjsongraph#15]
I am trying to change the default theme from: 
https://nodeshot.org/netjsongraph/examples/dark.html
to:
https://nodeshot.org/netjsongraph/examples/index.html

with no success. reading @ https://github.com/interop-dev/netjsongraph.js under the Styling section didn't enlighten me that much.

any hints would be much appreciated.

**Comment by nemesisdesign** [comment]
@acoul this feature is not supported right now, but I would happily introduce asap it if you are still using this app.

**Comment by rohithasrk** [comment]
@nemesisdesign We can add the css customization feature to the app as we've discussed earlier, what do you think?

**Comment by nemesisdesign** [comment]
@rohithasrk what do you have in mind?

**Comment by rohithasrk** [comment]
@nemesisdesign, I think I misinterpreted it. What I was talking about, is to allow css customization by users from the admin panel itself. The two important things we'll need to customize is Node and Link. So, we'll have to take the colors pertaining to nodes with lesser links, moderate and high links from the user, setting some default values if not provided.

**Comment by nemesisdesign** [comment]
@rohithasrk we should add the following things:

- a setting that can be used to supply a custom CSS file, which defaults to the one used now (https://github.com/netjson/django-netjsongraph/blob/master/django_netjsongraph/static/netjsongraph/style.css)
- ensure it's possible to override the default visualizer template, probably using the common way in django of creating a new directory with the modified template and add it to `TEMPLATES['DIRS']`, if something prevents this, we should fix it; then we need to add a short *How To* section in the README

**Comment by rohithasrk** [comment]
@nemesisdesign Ensured that it is possible to override the default template by using the trivial way of django as mentioned above. Is there any need to add a _how to_ section?

**Comment by nemesisdesign** [comment]
@rohithasrk yes we need to add the new settings to the README in the [SETTINGS section in the README](https://github.com/netjson/django-netjsongraph#settings)). See my comments in your pull request.

**Comment by nemesisdesign** [comment]
@rohithasrk after merging #30, we need to find an easy way to override the javascript instructions of the visualizer HTML template.

We probably don't need to write code, django already allows this, you could try to create a dir in the test project, put it in `TEMPLATES['DIRS']`, then create a template that overrides `netjsongraph/detail.html` - or try a variation of this procedure that works, when you have something that works, you could add a short how to in the README and then we are done with this.

**Comment by rohithasrk** [comment]
Yes. @nemesisdesign Tried doing it and it works. I'll add a short description

**Comment by nemesisdesign** [comment]
Ok cool, I think we are done with this! 👍 
@acoul enjoy :-)
