### ISSUE TITLE
update outdated requirement (django-rest-framework)

### ISSUE THREAD

**Issue by nemesisdesign** [netjson/django-netjsongraph#17]
update and test outdated requirement (django-rest-framework).

**Comment by rohithasrk** [comment]
Porting into the latest version of django-rest-framework?

**Comment by nemesisdesign** [comment]
Yes, we should update the minimum version in the requirements file and run the tests

**Comment by rohithasrk** [comment]
@nemesisdesign What shall we set the minimum version too? 3.4? I'm not so clear about how we can figure out the minimum version.

**Comment by nemesisdesign** [comment]
@rohithasrk leave the minimum version unchanged, put a higher maximum version.

You have to do it here:
https://github.com/netjson/django-netjsongraph/blob/master/requirements.txt

Because that file is read by the setupy.py script:
https://github.com/netjson/django-netjsongraph/blob/master/setup.py#L45

Please run the test suite on your local clone with the latest drf version first, to check if there is any error.
