### ISSUE TITLE
[feature] Topology history (snapshots - way back machine)

### ISSUE THREAD

**Issue by nemesisdesign** [netjson/django-netjsongraph#32]
Implement a way to save daily snapshots of the network topology so users can go back in time and analyse the status of the network in specific past dates.

A switcher in the visualizer shall be added to modify the date of the topology, the switcher should default to "latest" but has to allow to go back in time.

**Comment by rohithasrk** [comment]
@nemesisdesign I'm thinking to implement it by defining:
- [ ] A model named `Snapshot` with the fields, date, topology and data
- [ ] A function named `save_snapshot` which saves the network graph data in string format by retrieving it from the API.
- [ ] A script that will be run by a cron to trigger the `save_snapshot` function.
- [ ] A switcher view which will return the topology data using date and topology.

My doubts are:
* Should a cron be written in **django-netjsongraph** or will that be called from openwisp2? Or maybe both?
* How should a switcher look? A date picking tool maybe?
*

**Comment by nemesisdesign** [comment]
I will focus on replying to the other outstanding issues first, which I hope we can address asap so we can start deploying this app in the openwisp2 ecosystem very soon.

Ping me again on this issue when we have finished the other issues.

**Comment by nemesisdesign** [comment]
@rohithasrk I'm replying to these questions and other on the [OpenWISP chat](https://gitter.im/openwisp/general), please update this issue when we have finished discussing

**Comment by rohithasrk** [comment]
After discussing about the feature with @nemesisdesign, we've come to the following conclusions. We will be defining:
- [ ]  A model named `Snapshot` with the fields: date, topology and data
- [ ] A new class function named `save_snapshot()` of the topology model, which saves the network graph data in string format by retrieving it from the API.
- [ ] A new API url/view pair. The url being of the form `/api/v1/topology/<uuid>/history/?date=<date>` and the view querying the database and returning the data in NetJSON format.
- [ ] The switcher will be a date picking tool and a script checking out for the change events which could help generate the network topology graph.
- [ ] A command `save_snapshot` just like `update_topology`.
- [ ] A test suite for the above implementation.

As of now, this is the simplest implementation of the feature and has limitations such as one saving only one snapshot of topology per day, i.e., the data will be overwritten if the `save_snapshot` function is called more than once in a single day.

**Comment by nemesisdesign** [comment]
@rohithasrk great summary, proceed! 👍

**Comment by leonardomaccari** [comment]
Hi, 
a couple of years ago I did something similar to save snapshots of the topology and to make some stats:

https://github.com/leonardomaccari/django-netjsongraph
https://github.com/leonardomaccari/django_easy_network_stats

don't expect great code (my first Django experience) but you may get some ideas.

**Comment by nemesisdesign** [comment]
@leonardomaccari thanks for refreshing my memory, where did you store the data? I see an update model but I can't find where exactly the graph data is stored

**Comment by nemesisdesign** [comment]
@leonardomaccari technical discussion is going ahead on pull request #49
