### ISSUE TITLE
Improve reusability of API tests and others

### ISSUE THREAD

**Issue by rohithasrk** [netjson/django-netjsongraph#40]
The bugs haven't been discovered until launched to production. So, the tests being reusable would always be helpful.

**Comment by nemesisdesign** [comment]
We probably have to get rid of the fixtures and replace them with [methods like the ones used in django-netjsonconfig](https://github.com/openwisp/django-netjsonconfig/blob/master/django_netjsonconfig/tests/__init__.py#L12-L30).

**Comment by nemesisdesign** [comment]
@rohithasrk if this is done, please close
