### ISSUE TITLE
Refactor the update function of topology class

### ISSUE THREAD

**Issue by rohithasrk** [netjson/django-netjsongraph#41]
django-netjsongraph has been extended in [openwisp-network-topology](https://github.com/openwisp/openwisp-network-topology) with multi-tenancy. Therefore, an additional field i.e., an organization field is being added to all the three base models i.e., Node, Link and Topology.

The task is to make the update function reusable so that the code duplication is minimum.

**Comment by rohithasrk** [comment]
#42 Has the code which references this issue. When integrated into [openwisp-network-topology](https://github.com/openwisp/openwisp-network-topology) the error pops up in the `update` function of topology class and that's the reason `fetch` and `receive` don't work.

**Comment by nemesisdesign** [comment]
@rohithasrk is this done right? If yes, close this please.
