### ISSUE TITLE
[tests] Make all the tests reusable

### ISSUE THREAD

**Issue by rohithasrk** [netjson/django-netjsongraph#47]
As of now only api and admin tests are reusable. We might need to make the others reusable too.

**Comment by nemesisdesign** [comment]
We should also move the tests in something like `tests.base` and create one file for each class, otherwise `tests.utils` would become too long and hard to read.

**Comment by rohithasrk** [comment]
True @nemesisdesign.

**Comment by nemesisdesign** [comment]
👍
