### ISSUE TITLE
no such table: django_netjsongraph_snapshot

### ISSUE THREAD

**Issue by acoul** [netjson/django-netjsongraph#57]
this is on a freshly synced gentoo 32-bit system

Edit: missed this part:
I used the CLI to create the database:

> ./manage.py migrate
./manage.py createsuperuser

then I tried to delete it from the admin/web panel and I got the following:

> django-netjsongraph (0.3.4)  - Reusable django app for collecting and visualizing network topology
  INSTALLED: 0.3.4 (latest)
creating the database from the CLI

> ./manage.py migrate
and then trying to delete it from the admin web interface, I get:

> Django Version: 1.11.2
Python Version: 3.4.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'openwisp_utils.admin_theme',
 'django_netjsongraph']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

> OperationalError at /admin/django_netjsongraph/topology/

> no such table: django_netjsongraph_snapshot

**Comment by nemesisdesign** [comment]
@acoul what are you trying to delete?

**Comment by acoul** [comment]
updated the first post

**Comment by nemesisdesign** [comment]
@acoul I'm sorry, I still don't understand what object you are trying to delete and is giving you the error:

> then I tried to delete it from the admin/web panel and I got the following:

Could you please clarify what does "it" refers to?

**Comment by acoul** [comment]
I tried to delete the whole database from the admin/web GUI

I suspect that I may have a mixed stable/snapshot django-netjsongraph installation on my gentoo system. I will further investigate this and do a follow-up.

**Comment by nemesisdesign** [comment]
Likely. If you find a bug that is possible to replicate let me know. I don't have any good suggestion with the current info. Fed

**Comment by acoul** [comment]
it was a mixed stable/snapshot django-netjsongraph installation. straighting this out produced a fully operational result. Sorry for the noise.
