### ISSUE TITLE
orphan nodes

### ISSUE THREAD

**Issue by acoul** [netjson/django-netjsongraph#59]
Some nodes may appear on the [output graph](http://nmsbgp.ozo.com/topology/470bf7bf-604b-4114-83e2-17eac0c91ebf/) as orphans while they have a proper entriy in the [NetJSON](http://dev.ozo.com/awmn.json) input file.

For example:

> id: alex, rawAs: 20399

**Comment by nemesisdesign** [comment]
@acoul I can't load the graph. Plus the size of your data is so huge that it's hard to debug.
The best approach when working on bugs is to isolate it. Do you have an idea of how to replicate the bug in a controlled environment?

**Comment by acoul** [comment]
I created a smaller subset of [NetJSON](http://spq.ozo.com/awmn-test.json) nodes. The orphan issue does not appear in this smaller subset, but the issue on https://github.com/netjson/django-netjsongraph/issues/58 remains.

can you perhaps test this smaller subset and see if you get similar behavior?

**Comment by nemesisdesign** [comment]
Using that subset I don't see any orphan, regarding the issue in #58, that's a different matter, let's discuss it there so it's easier to track the discussion.

**Comment by nemesisdesign** [comment]
Let me know if #62 resolves this too.

**Comment by acoul** [comment]
I followed the patch update steps as explained in https://github.com/netjson/django-netjsongraph/issues/58 and I deleted the orphan nodes from the admin panel. I then updated the db and now those nodes are totally missing at the graph, while appearing in the json file. Here is an example of such a node: "grep -w nios -B 2 -A 2 awmn.json"

      "source": "ncksm", 
      "cost": 1.0, 
      "target": "nios", 
      "cost_text": "", 
      "properties": {}

        "rawAs": "15716"
      }, 
      "id": "nios", 
      "label": "nios"
    }, 
    {

**Comment by nemesisdesign** [comment]
Closed by #79
