### ISSUE TITLE
netjsongraph

### ISSUE THREAD

**Issue by deugeu** [netjson/django-netjsongraph#65]
Hello i'm developing a application django who will use netjsongraph.
So my problem is why  to put the url  json in d3.netJsonGraph()
i tried all means but i can not.
can anyone help me please
Thanks you f

**Comment by nemesisdesign** [comment]
Hi @deugeu, I haven't understood your question well, could you expand a bit?

**Comment by deugeu** [comment]
Hi  @nemesisdesign ! I need to put the json's link in my HTML file, so I wonder how can I configure the json link in the d3.netJsonGraph()

Ex : d3.netJsonGraph({ % static './data/netjson.json'%})

I tried with this exemple but it doesn't work, could you please help me to find out how to configure the json's link in  d3.netJsonGraph() ?

Thanks you !

**Comment by nemesisdesign** [comment]
@deugeu, do you need to customize the HTML <script> tag? If the answer is yes, please see: https://github.com/netjson/django-netjsongraph#example-overriding-the-script-tag
If the answer is no, try be more specific so I can help you better, because I'm still not getting why would you need to do that (data is taken from the database, if you need to load data, import it in a Topology).

**Comment by deugeu** [comment]
Hi @nemesisdesign ! I created a function following on view will get the data on database 

def data_json(request):

    data_nodes = []
    data_links = []
    query_nodes = Nodes.objects.all()
    query_links = links.objects.all()
    for link in query_links:
        data_links.append({"source":link.source,
                           "target":link.target,
                           "cost":link.cost
                           })
    for node in query_nodes:
        data_nodes.append({"id":node.ip_address,
                           "label": node.label
                           })
    netjson = OrderedDict((
        ('nodes', data_nodes),
        ('links', data_links)
    ))
    data = json.dumps(netjson, indent=2 ,sort_keys=True)
    return HttpResponse(data, content_type='application/json')


And to send results the format json in the page HTML ( link 127.0.0.1/data_json) 
# results
{
  "links": [
    {
      "cost": 1.0,
      "source": "172.16.146.1",
      "target": "172.16.145.2"
    },
    {
      "cost": 1.0,
      "source": "172.16.146.1",
      "target": "172.16.146.4"
    },
    {
      "cost": 1.0,
      "source": "172.16.146.1",
      "target": "172.16.146.5"
    },
    {
      "cost": 1.0,
      "source": "172.16.146.1",
      "target": "172.16.146.6"
    },
    {
      "cost": 1.0,
      "source": "172.16.146.1",
      "target": "172.16.146.8"
    }
  ],
  "nodes": [
    {
      "id": "172.16.146.6",
      "label": null
    },
    {
      "id": "172.16.145.2",
      "label": null
    },
    {
      "id": "172.16.146.4",
      "label": null
    },
    {
      "id": "172.16.146.1",
      "label": null
    },
    {
      "id": "172.16.146.5",
      "label": null
    }
  ]
}
so i want put the link json example(127.0.0.1/data_json)  on d3.netJsonGraph(**HERE)** as you did with API framework_rest
