### ISSUE TITLE
Vagrant 

### ISSUE THREAD

**Issue by MiHiR151203** [netjson/django-netjsongraph#76]
Sir, How Can I Install OpenWISP Network Topology Using Vagrant

**Comment by UtkarshVerma** [comment]
Actually, there's a Vagrantfile to be made.

**Comment by UtkarshVerma** [comment]
Are you on gitter?

**Comment by MiHiR151203** [comment]
Yes

**Comment by UtkarshVerma** [comment]
Contact me there, @UtkarshVerma

**Comment by MiHiR151203** [comment]
Sir how can i find you there are 3 people named Utkarsh Verma

**Comment by UtkarshVerma** [comment]
Join the openwisp gitter room here: https://gitter.im/openwisp/general
