### ISSUE TITLE
attribute of 'TopologyAdmin'

### ISSUE THREAD

**Issue by sah-anshu** [netjson/django-netjsongraph#90]
Hi
Please advice me on this issue. 

<class 'django_netjsongraph.admin.TopologyAdmin'>: (admin.E108) The value of 'list_display[6]' refers to 'organization', which is not a callable, an attribute of 'TopologyAdmin', or an attribute or method on 'django_netjsongraph.Topology'.

Thanks in advance.

**Comment by nemesisdesign** [comment]
This module doesn't have any `organization` attribute, OpenWISP does adds that on the [openwisp-network-topology](https://github.com/openwisp/openwisp-network-topology) module (which uses this module as a base), but I don't have enough information to be able to help you. Please use the [OpenWISP Support channels](http://openwisp.org/support.html) if you need help with questions related to OpenWISP.
